#!/usr/bin/env python3
"""Data schema summary for the Scout (M09; Stage 2 with stage2.prediction_cards).

Writes knowledge/data_schema.md: every parquet table in the KNA processed
directory (KBL_DATA, else the default KNA install location) and in the repo's data/
folder, with its columns, dtypes and row count. It reads parquet metadata
only and never prints a value, so the Scout can write a specification plan
against real column names without seeing the data. Locations are written as
labels, never as absolute paths, because the file is public.

Usage:
    python3 data_schema.py                 # write knowledge/data_schema.md
    python3 data_schema.py --print         # print instead of writing
"""

import argparse
import os
from datetime import datetime, timezone
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
OUT_FILE = BASE_DIR / "knowledge" / "data_schema.md"


def default_sources() -> list[tuple[str, Path]]:
    """[(label, directory)] in the order they are documented."""
    kna = os.environ.get("KBL_DATA")
    kna_dir = Path(kna).expanduser() if kna else Path.home() / "kna" / "data" / "processed"
    return [("KNA processed data (KBL_DATA)", kna_dir), ("kr-hearings data (data/)", BASE_DIR / "data")]


def table_schema(path: Path) -> dict:
    """{"name", "rows", "columns": [(name, dtype)]} from parquet metadata only."""
    import pyarrow.parquet as pq
    f = pq.ParquetFile(path)
    return {"name": path.name, "rows": f.metadata.num_rows,
            "columns": [(fld.name, str(fld.type)) for fld in f.schema_arrow]}


def render(sources: list[tuple[str, Path]] | None = None) -> str:
    sources = sources if sources is not None else default_sources()
    lines = ["# Data schema", "",
             f"Generated by data_schema.py on {datetime.now(timezone.utc).date().isoformat()} from "
             "parquet metadata. Tables, columns, dtypes and row counts only, no values. Write "
             "card specifications against these column names.", ""]
    for label, d in sources:
        files = sorted(d.glob("*.parquet")) if d.exists() else []
        lines += [f"## {label}", ""]
        if not files:
            lines += ["Not available on this machine.", ""]
            continue
        for p in files:
            try:
                t = table_schema(p)
            except Exception as e:  # unreadable file: name it, do not stop
                lines += [f"### {p.name}", "", f"Unreadable ({type(e).__name__}).", ""]
                continue
            lines += [f"### {t['name']} ({t['rows']:,} rows)", "", "| Column | Type |", "|---|---|"]
            lines += [f"| {c} | {ty} |" for c, ty in t["columns"]]
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write(out: Path | None = None, sources: list[tuple[str, Path]] | None = None) -> Path:
    out = out or OUT_FILE
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(sources), encoding="utf-8")
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description="Write knowledge/data_schema.md (no values)")
    ap.add_argument("--print", action="store_true", dest="to_stdout")
    args = ap.parse_args()
    if args.to_stdout:
        print(render())
    else:
        print(f"wrote {write()}")


if __name__ == "__main__":
    main()
