#!/usr/bin/env python3
"""
Article Drafting Pipeline
=========================
Auto-triggered when Critic gives a "pursue" verdict.
Generates a working paper draft from forum findings.

Usage:
    python3 draft_article.py                    # Auto-detect pursue verdicts
    python3 draft_article.py --round 4          # Draft from specific round
    python3 draft_article.py --list             # List pursue verdicts
"""

import argparse
import json
import re
import subprocess
import sys
import textwrap
from datetime import datetime
from pathlib import Path

BASE_DIR = Path(__file__).parent
FORUM_DIR = BASE_DIR / "forum"
ARTICLES_DIR = BASE_DIR / "articles"
KNOWLEDGE_DIR = BASE_DIR / "knowledge"
WORKSPACE_DIR = BASE_DIR / "workspace"
SUMMARIES_DIR = BASE_DIR / "summaries"

import os
import shutil

CLAUDE = shutil.which("claude") or str(Path.home() / ".local" / "bin" / "claude")


def find_pursue_verdicts():
    """Find all rounds where Critic gave a 'pursue' verdict."""
    findings_file = KNOWLEDGE_DIR / "findings.jsonl"
    if not findings_file.exists():
        return []

    pursues = []
    with open(findings_file) as f:
        for line in f:
            try:
                entry = json.loads(line)
                if entry.get("verdict") == "pursue":
                    pursues.append(entry)
            except json.JSONDecodeError:
                pass
    return pursues


def get_round_posts(round_num):
    """Get all posts from a specific round."""
    posts = sorted(FORUM_DIR.glob("*.md"))
    n_agents = 3
    start = (round_num - 1) * n_agents
    end = round_num * n_agents
    round_posts = posts[start:end]
    return [p.read_text() for p in round_posts]


def get_all_forum_context(up_to_round):
    """Get compressed forum context. Full text for last 2 rounds, summaries for older."""
    posts = sorted(FORUM_DIR.glob("*.md"))
    n_agents = 3
    context = []

    # Include round summaries for older rounds (much shorter than full posts)
    for sf in sorted(SUMMARIES_DIR.glob("round_*.md")):
        rnd_num = int(re.search(r"(\d+)", sf.stem).group(1))
        if rnd_num <= up_to_round - 2:
            context.append(f"--- Round {rnd_num} Summary ---\n{sf.read_text()}")

    # Full text for last 2 rounds only
    for i, p in enumerate(posts):
        rnd = (i // n_agents) + 1
        if rnd > up_to_round:
            break
        if rnd >= up_to_round - 1:
            context.append(f"--- {p.name} ---\n{p.read_text()}")

    return "\n\n".join(context)


def draft_article(round_num):
    """Generate a working paper draft from forum findings."""
    ARTICLES_DIR.mkdir(exist_ok=True)
    WORKSPACE_DIR.mkdir(exist_ok=True)

    ts = datetime.now().strftime("%Y-%m-%d")
    forum_context = get_all_forum_context(round_num)

    # Check for existing articles to avoid duplicates
    existing = list(ARTICLES_DIR.glob(f"*_r{round_num}.tex")) + list(ARTICLES_DIR.glob(f"*_r{round_num}.md"))
    existing = [e for e in existing if "template" not in e.name and "content" not in e.name]
    if existing:
        print(f"  Article for round {round_num} already exists: {existing[0].name}")
        return existing[0]

    article_slug = f"{ts}_r{round_num}"
    tex_file = ARTICLES_DIR / f"{article_slug}.tex"
    content_file = ARTICLES_DIR / f"{article_slug}_content.tex"

    prompt = textwrap.dedent(f"""\
    You are a research paper drafting agent. Based on the forum discussion below,
    draft a working paper as a LaTeX document body following APSR conventions.

    IMPORTANT: Write ONLY the LaTeX body content (from \\title to the bibliography).
    Do NOT include \\documentclass, \\usepackage, or \\begin{{document}}.
    The template handles those.

    Write the content to: {content_file}

    ## OUTPUT FORMAT (LaTeX body only)

    Write this exact structure:

    \\title{{[Paper Title]}}
    \\author{{KNA Research Agents (AI-generated)}}
    \\affil{{Experimental Output --- kna-research-agents.com}}
    \\date{{\\today}}
    \\maketitle
    \\thispagestyle{{empty}}

    \\begin{{abstract}}
    \\noindent [150 words. Question, method, key finding, contribution.]
    \\end{{abstract}}

    \\bigskip
    \\setcounter{{page}}{{0}}
    \\clearpage

    \\section{{Introduction}}
    [~1000 words. Theoretical puzzle, gap, this paper, preview.]

    \\section{{Literature and Theory}}
    [~1200 words. Engage with work, derive expectations.]

    \\section{{Data and Method}}
    [~800 words. KNA database, variables, identification.]

    \\subsection{{Data}}
    [Describe KNA: N bills, time period, unit of analysis.]

    \\subsection{{Identification Strategy}}
    [Formal equation + variable definitions.]

    \\section{{Results}}
    [~1000 words. Tables + interpretation.]

    \\section{{Discussion}}
    [~600 words. Theory connection, limitations.]

    \\section{{Conclusion}}
    [~400 words. Contribution, implications.]

    \\bigskip
    \\noindent\\textit{{This working paper was generated by AI research agents as an
    experimental output. It has not been peer-reviewed or fact-checked.
    Do not cite or use in any academic, policy, or professional context.}}

    ## APSR STYLE (strict)

    **Voice**: Use "I" throughout. Active voice. Theory=present, analysis=past, results=present.
    **Introduction**: Start with theoretical puzzle. NEVER "In recent years..." NEVER "This is the first paper to..."
    **Gap**: "there exists, to our knowledge, no study..." or "Despite X, there is a lack of..."

    **Citations (natbib commands):**
    - Narrative: \\citet{{cox2005}} = Cox and McCubbins (2005)
    - Parenthetical: \\citep{{lowi1964}} = (Lowi 1964)
    - Multiple: \\citep{{bates1998, jones1990}} = (Bates et al. 1998; Jones 1990)
    - With page: \\citep[45]{{author2005}} = (Author 2005, 45)
    - Since we have no .bib file, FAKE the citations by writing them manually:
      Instead of \\citet{{cox2005}}, write: Cox and McCubbins (2005)
      Instead of \\citep{{lowi1964}}, write: (Lowi 1964)

    **Equations (amsmath):**
    Inline: $\\beta_1$, $p < 0.001$
    Display:
    \\begin{{equation}}
    \\Pr(\\text{{Decision}}_i = 1) = \\Lambda(\\beta_1 \\text{{Minsaeng}}_i + \\mathbf{{X}}_i \\boldsymbol{{\\gamma}} + \\delta_c + \\epsilon_i)
    \\label{{eq:main}}
    \\end{{equation}}
    Reference: Equation~\\ref{{eq:main}}

    **Tables (booktabs, MANDATORY at least 2):**
    \\begin{{table}}[H]
    \\centering
    \\caption{{Descriptive Statistics}}
    \\label{{tab:desc}}
    \\begin{{tabular}}{{lcccc}}
    \\toprule
    Variable & N & Mean & SD & Range \\\\
    \\midrule
    ... & ... & ... & ... & ... \\\\
    \\bottomrule
    \\end{{tabular}}
    \\end{{table}}

    Regression table:
    \\begin{{table}}[H]
    \\centering
    \\caption{{Main Results: Committee Processing of Bills}}
    \\label{{tab:main}}
    \\begin{{tabular}}{{lccc}}
    \\toprule
    & (1) & (2) & (3) \\\\
    & Baseline & Controls & FE \\\\
    \\midrule
    Minsaeng & $-0.093^{{***}}$ & $-0.085^{{***}}$ & $-0.078^{{***}}$ \\\\
    & (0.008) & (0.009) & (0.010) \\\\
    ... \\\\
    \\midrule
    N & 50,003 & 50,003 & 50,003 \\\\
    Committee FE & No & No & Yes \\\\
    Pseudo $R^2$ & 0.04 & 0.08 & 0.12 \\\\
    \\bottomrule
    \\multicolumn{{4}}{{l}}{{\\footnotesize $^*p<0.10$, $^{{**}}p<0.05$, $^{{***}}p<0.01$. SE in parentheses.}} \\\\
    \\end{{tabular}}
    \\end{{table}}

    **Statistics in text:**
    $\\beta = -0.093$ (SE $= 0.008$, $p < 0.001$)

    **Causal language:**
    OLS: "is associated with". DiD/RD: "the effect of". NEVER "proves".

    **References section:**
    Since no .bib file, write references manually at the end:
    \\section*{{References}}
    \\begin{{description}}
    \\item Cox, Gary W., and Mathew D. McCubbins. 2005. \\textit{{Setting the Agenda}}. New York: Cambridge University Press.
    \\item Lowi, Theodore J. 1964. ``American Business, Public Policy, Case-Studies, and Political Theory.'' \\textit{{World Politics}} 16 (4): 677--715.
    \\end{{description}}
    ONLY include references from the forum posts.

    RULES:
    - ONLY use findings/statistics/references from the forum posts below
    - Do NOT invent data or citations
    - Acknowledge Critic's limitations honestly
    - Target 5,000-6,000 words
    - Valid LaTeX that compiles with xelatex

    ## Forum Discussion (Rounds 1-{round_num})

    {forum_context}
    """)

    prompt_file = WORKSPACE_DIR / "_prompt_article.md"
    prompt_file.write_text(prompt)

    print(f"\n  Drafting article from Round {round_num}...")
    print(f"  Output: {tex_file}")

    cmd = [
        CLAUDE, "-p",
        "--allowedTools", "Write",
        "--dangerously-skip-permissions",
        "--system-prompt-file", str(prompt_file),
        "--output-format", "text",
        "Write the working paper draft now.",
    ]

    try:
        result = subprocess.run(
            cmd, capture_output=True, text=True, timeout=1200,
            cwd=str(WORKSPACE_DIR),
        )
        if content_file.exists():
            content = content_file.read_text()
            wc = len(content.split())
            print(f"  Content generated: {wc} words")

            # Merge with template
            template = (ARTICLES_DIR / "template.tex").read_text()
            # Extract title for markdown version
            import re as _re
            title_match = _re.search(r'\\title\{(.+?)\}', content)
            title = title_match.group(1) if title_match else "Untitled"

            full_tex = template.replace("%%TITLE%%", "").replace("%%CONTENT%%", content)
            tex_file.write_text(full_tex)
            print(f"  LaTeX: {tex_file.name}")

            # Also save a markdown version for the website
            md_file = ARTICLES_DIR / f"{article_slug}.md"
            md_file.write_text(
                f"---\ntitle: \"{title}\"\nauthors: \"KNA Research Agents\"\n"
                f"date: \"{ts}\"\nsource_round: {round_num}\nstatus: \"experimental draft\"\n"
                f"tex_file: \"{tex_file.name}\"\n---\n\n"
                f"# {title}\n\n"
                f"**KNA Research Agents** | AI-Generated Working Paper | {ts}\n\n"
                f"Source: Forum Round {round_num} | Status: Experimental Draft\n\n"
                f"[View LaTeX source]({tex_file.name}) | "
                f"[Download PDF]({article_slug}.pdf)\n\n---\n\n"
                f"*See PDF for full paper with equations, tables, and references.*\n"
            )

            # Compile with xelatex
            try:
                compile_tex(tex_file)
            except Exception as e:
                print(f"  PDF compilation failed: {e}")

            # Clean up content file
            content_file.unlink()
            return tex_file
        else:
            print(f"  WARNING: Article not generated")
            return None
    except subprocess.TimeoutExpired:
        print(f"  TIMEOUT")
        return None


def compile_tex(tex_file):
    """Compile LaTeX to PDF using xelatex."""
    import subprocess as _sp

    tex_dir = tex_file.parent
    print(f"  Compiling {tex_file.name} with xelatex...")

    # Run xelatex twice (for references/cross-refs)
    for i in range(2):
        result = _sp.run(
            ["xelatex", "-interaction=nonstopmode", "-halt-on-error", tex_file.name],
            capture_output=True, text=True, timeout=120, cwd=str(tex_dir),
        )
        if result.returncode != 0 and i == 0:
            # First pass may fail on refs, try once more
            continue
        elif result.returncode != 0 and i == 1:
            print(f"  xelatex error (pass {i+1})")
            # Save error log
            log = tex_dir / tex_file.stem
            err_lines = result.stdout.split("\n")
            errors = [l for l in err_lines if l.startswith("!") or "Error" in l]
            for e in errors[:5]:
                print(f"    {e}")

    pdf_file = tex_file.with_suffix(".pdf")
    if pdf_file.exists():
        print(f"  PDF: {pdf_file.name} ({pdf_file.stat().st_size // 1024} KB)")
        # Clean aux files
        for ext in [".aux", ".log", ".out", ".toc"]:
            f = tex_file.with_suffix(ext)
            if f.exists():
                f.unlink()
    else:
        print(f"  WARNING: PDF not generated")


def main():
    parser = argparse.ArgumentParser(description="Article Drafting Pipeline")
    parser.add_argument("--round", type=int, help="Draft from specific round")
    parser.add_argument("--list", action="store_true", help="List pursue verdicts")
    args = parser.parse_args()

    if args.list:
        pursues = find_pursue_verdicts()
        if not pursues:
            print("No 'pursue' verdicts found.")
        for p in pursues:
            print(f"  Round {p['round']}: {p['finding'][:80]}... [{p['verdict']}]")
        return

    if args.round:
        draft_article(args.round)
        return

    # Auto-detect: find pursue verdicts without existing articles
    pursues = find_pursue_verdicts()
    if not pursues:
        print("No 'pursue' verdicts found. Run more forum rounds.")
        return

    for p in pursues:
        rnd = p["round"]
        existing = list(ARTICLES_DIR.glob(f"*_r{rnd}_*.md"))
        if not existing:
            print(f"  Found pursue verdict for Round {rnd}")
            draft_article(rnd)
        else:
            print(f"  Round {rnd}: article already exists ({existing[0].name})")


if __name__ == "__main__":
    main()
