#!/usr/bin/env python3
"""
Conference Generator
====================
Auto-triggered every 20 cumulative forum rounds.
Generates a structured academic conference from all forum findings and articles.

Usage:
    python3 generate_conference.py              # Auto-detect if ready
    python3 generate_conference.py --force      # Force generation
"""

import argparse
import json
import subprocess
import textwrap
from datetime import datetime
from pathlib import Path

BASE_DIR = Path(__file__).parent
FORUM_DIR = BASE_DIR / "forum"
ARTICLES_DIR = BASE_DIR / "articles"
SUMMARIES_DIR = BASE_DIR / "summaries"
ARCHIVE_DIR = BASE_DIR / "forum_archive"
WORKSPACE_DIR = BASE_DIR / "workspace"
KNOWLEDGE_DIR = BASE_DIR / "knowledge"

import shutil
CLAUDE = shutil.which("claude") or str(Path.home() / ".local" / "bin" / "claude")


def count_cumulative_rounds():
    """Count total rounds across current forum + archives."""
    current = len(list(SUMMARIES_DIR.glob("round_*.md"))) if SUMMARIES_DIR.exists() else 0
    archived = 0
    if ARCHIVE_DIR.exists():
        for d in ARCHIVE_DIR.iterdir():
            if d.is_dir():
                archived += len(list(d.glob("round_*.md")))
    return current + archived


def get_all_summaries():
    """Collect all round summaries (current + archived)."""
    summaries = []

    # Archived summaries
    if ARCHIVE_DIR.exists():
        for d in sorted(ARCHIVE_DIR.iterdir()):
            if d.is_dir():
                for s in sorted(d.glob("round_*.md")):
                    summaries.append(s.read_text())

    # Current summaries
    if SUMMARIES_DIR.exists():
        for s in sorted(SUMMARIES_DIR.glob("round_*.md")):
            summaries.append(s.read_text())

    return summaries


def get_all_articles():
    """Collect all published articles."""
    articles = []
    if ARTICLES_DIR.exists():
        for a in sorted(ARTICLES_DIR.glob("*.md")):
            articles.append(a.read_text()[:3000])  # First 3000 chars
    return articles


def generate_conference(conf_num=1):
    """Generate a conference proceedings document."""
    ARTICLES_DIR.mkdir(exist_ok=True)
    WORKSPACE_DIR.mkdir(exist_ok=True)

    ts = datetime.now().strftime("%Y-%m-%d")
    total_rounds = count_cumulative_rounds()

    summaries_text = "\n\n---\n\n".join(get_all_summaries())
    articles_text = "\n\n---\n\n".join(get_all_articles())

    prompt = textwrap.dedent(f"""\
    You are organizing an academic conference for the KNA Research Agents forum.
    This is Conference #{conf_num}, triggered after {total_rounds} cumulative forum rounds.

    Generate a conference proceedings document that synthesizes all research
    conducted by the forum agents.

    Write to: {ARTICLES_DIR}/conference_{conf_num}_{ts}.md

    Format:

    ```markdown
    ---
    title: "KNA Research Agents Conference #{conf_num}"
    date: "{ts}"
    type: "conference_proceedings"
    total_rounds: {total_rounds}
    ---

    # KNA Research Agents Conference #{conf_num}

    **Proceedings** | {ts} | {total_rounds} Forum Rounds

    ---

    ## Keynote: State of KNA Research

    [Scout delivers a keynote synthesizing the literature landscape across all
    rounds. What questions were asked? What gaps were filled? What remains open?
    ~500 words.]

    ## Panel 1: Empirical Findings

    [Analyst presents the key empirical discoveries across all rounds.
    Organize by theme. Include the strongest statistics. ~600 words.]

    ## Panel 2: Theoretical Contributions

    [Scout presents how the forum's findings connect to political science theory.
    What theoretical predictions were tested? Which were confirmed/rejected? ~500 words.]

    ## Discussant Response

    [Critic provides a unified methodological assessment. What was done well?
    What are the remaining identification challenges? ~500 words.]

    ## Roundtable: Research Agenda

    [All agents contribute to a forward-looking research agenda.
    Top 5 research questions for the next 20 rounds. ~400 words.]

    ## Conference Summary

    [2-3 paragraph synthesis of the conference. Key takeaways for a reader
    who hasn't followed the forum. ~200 words.]

    ## Published Articles

    [List all articles produced by the forum, with titles and round sources.]

    ---

    *Conference proceedings generated by AI research agents.*
    *All findings are experimental and have not been peer-reviewed.*
    ```

    RULES:
    - Use ONLY findings from the forum summaries and articles below
    - APSA citation style throughout
    - Be synthetic, not repetitive - don't just re-list findings
    - Target 3,000 words total

    ## Round Summaries

    {summaries_text}

    ## Published Articles

    {articles_text}
    """)

    prompt_file = WORKSPACE_DIR / "_prompt_conference.md"
    prompt_file.write_text(prompt)

    print(f"\n  Generating Conference #{conf_num} ({total_rounds} rounds)...")

    cmd = [
        CLAUDE, "-p",
        "--allowedTools", "Write",
        "--dangerously-skip-permissions",
        "--system-prompt-file", str(prompt_file),
        "--output-format", "text",
        "Write the conference proceedings now.",
    ]

    try:
        result = subprocess.run(
            cmd, capture_output=True, text=True, timeout=600,
            cwd=str(WORKSPACE_DIR),
        )
        conf_file = ARTICLES_DIR / f"conference_{conf_num}_{ts}.md"
        if conf_file.exists():
            wc = len(conf_file.read_text().split())
            print(f"  Conference #{conf_num}: {conf_file.name} ({wc} words)")
            return conf_file
        else:
            print(f"  WARNING: Conference not generated")
            return None
    except subprocess.TimeoutExpired:
        print(f"  TIMEOUT")
        return None


def main():
    parser = argparse.ArgumentParser(description="Conference Generator")
    parser.add_argument("--force", action="store_true", help="Force generation")
    args = parser.parse_args()

    total = count_cumulative_rounds()
    existing = len(list(ARTICLES_DIR.glob("conference_*.md"))) if ARTICLES_DIR.exists() else 0
    threshold = (existing + 1) * 20

    print(f"  Cumulative rounds: {total}")
    print(f"  Conferences held: {existing}")
    print(f"  Next conference at: {threshold} rounds")

    if total >= threshold or args.force:
        generate_conference(existing + 1)
    else:
        print(f"  Not yet ({total}/{threshold} rounds). Use --force to override.")


if __name__ == "__main__":
    main()
